Pin `arrow`-dependencies to version 52 or 53 (#13)
Hi,

our CI lit up with errors like this:

```
error[E0277]: the trait bound `Arc<(dyn arrow::array::Array + 'static)>: From<Box<dyn re_arrow2::array::Array>>` is not satisfied
   --> /builds/straw/rust-cam/.cargo-proj/registry/src/index.crates.io-6f17d22bba15001f/re_types_core-0.21.0/src/archetype.rs:166:25
    |
166 |             (component, arrow::array::ArrayRef::from(arrow2_array))
    |                         ^^^^^^^^^^^^^^^^^^^^^^ the trait `From<Box<dyn re_arrow2::array::Array>>` is not implemented for `Arc<(dyn arrow::array::Array + 'static)>`
    |
    = help: the following other types implement trait `From<T>`:
              `Arc<B>` implements `From<Cow<'_, B>>`
              `Arc<CStr>` implements `From<&CStr>`
              `Arc<CStr>` implements `From<&mut CStr>`
              `Arc<CStr>` implements `From<CString>`
              `Arc<OsStr>` implements `From<&OsStr>`
              `Arc<OsStr>` implements `From<&mut OsStr>`
              `Arc<OsStr>` implements `From<OsString>`
              `Arc<Path>` implements `From<&Path>`
            and 14 others
error[E0277]: the trait bound `arrow::buffer::Buffer: From<re_arrow2::buffer::Buffer<T>>` is not satisfied
```

I believe this is because rerun 0.21 depends on arrow crates 53 but
re_arrow2 0.18 depends on arrow crates >=52. As arrow just released
version 54, this is now picked up by re_arrow2, but now clashes with the
arrow crates 53.

This PR sets the arrow crates version to 53.

---------

Co-authored-by: Emil Ernerfeldt <emil.ernerfeldt@gmail.com>